### ISSUE TITLE
[BUG] Default language model results in error if using a different API provider

### ISSUE THREAD

**Issue by theoforger** [mayank-Pareek/dev-mate-cli#4]
### Description
Because the default language model is hard coded as `google/gemma-2-9b-it:free`, which is a model id specific to OpenRouter, the default option is not compatible with other API providers.

### Environment
- **Operating System:** Fedora Workstation 40
- **Node.js Version:** v20.12.2
- **`npm` Version:** 10.5.0
- **Language Model Provider:** Groq

### Content of `.env` File

```
API_KEY=[Redacted]
BASE_URL=https://api.groq.com/openai/v1/
```

### To Reproduce
1. Use any API provider other than OpenRouter
2. Run: 
```bash
npm start ./examples/file.js
``` 
  Output:
```bash
> dev-mate-cli@0.1.0 start
> node dist/index.js ./examples/file.js

NotFoundError: 404 The model `google/gemma-2-9b-it:free` does not exist or you do not have access to it.
    at APIError.generate (/home/theoforger/dev-mate-cli/node_modules/openai/error.js:54:20)
    at OpenAI.makeStatusError (/home/theoforger/dev-mate-cli/node_modules/openai/core.js:275:33)
    at OpenAI.makeRequest (/home/theoforger/dev-mate-cli/node_modules/openai/core.js:318:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 404,
  headers: {
    'alt-svc': 'h3=":443"; ma=86400',
    'cache-control': 'private, max-age=0, no-store, no-cache, must-revalidate',
    'cf-cache-status': 'DYNAMIC',
    'cf-ray': '8c28df22fe87aaeb-YYZ',
    connection: 'keep-alive',
    'content-encoding': 'gzip',
    'content-type': 'application/json',
    date: 'Fri, 13 Sep 2024 14:36:48 GMT',
    server: 'cloudflare',
    'set-cookie': '__cf_bm=ywScje7WSd0FgGviGeK71meFkLYXpHWtST74xNb0WLU-1726238208-1.0.1.1-hVg7.FbOCce6.TYD5p8ERRDVTy60zyzPPu.xABpPEvt36W6k3DmsmnQ52QXYr3p94AtttKvjTj8UbLujIuyQkQ; path=/; expires=Fri, 13-Sep-24 15:06:48 GMT; domain=.groq.com; HttpOnly; Secure; SameSite=None',
    'transfer-encoding': 'chunked',
    vary: 'Origin',
    via: '1.1 google',
    'x-request-id': 'req_01j7nx1cg8eg286q6mep7jhykc'
  },
  request_id: 'req_01j7nx1cg8eg286q6mep7jhykc',
  error: {
    message: 'The model `google/gemma-2-9b-it:free` does not exist or you do not have access to it.',
    type: 'invalid_request_error',
    code: 'model_not_found'
  },
  code: 'model_not_found',
  param: undefined,
  type: 'invalid_request_error'
}

```

### Recommended Solutions
- Provide a config file, allowing users to set a default
- By default, prompt an interactive menu for users to choose a model

**Comment by mayank-Pareek** [comment]
Added model configuration file and removed mentions of OpenRouter as the sole model provider. Closed with commit [b59a912](https://github.com/mayank-Pareek/dev-mate-cli/commit/b59a9125aaffd950079bbc9d3cd5198e2a0a42d4)
