### ISSUE TITLE
`README.md` `.env` configuration instructions misleading

### ISSUE THREAD

**Issue by uday-rana** [mayank-Pareek/dev-mate-cli#8]
The `.env` configuration instructions in the `README.md` tell the user to use an OpenRouter API Key with the Base URL `https://api.openai.com/v1`, but this results in a 401 response.

```
AuthenticationError: 401 Incorrect API key provided: sk-or-v1*************************************************************abf1. You can find your API key at https://platform.openai.com/account/api-keys.
    at APIError.generate (/home/user/dev-mate-cli/node_modules/openai/error.js:48:20)
    at OpenAI.makeStatusError (/home/user/dev-mate-cli/node_modules/openai/core.js:275:33)
    at OpenAI.makeRequest (/home/user/dev-mate-cli/node_modules/openai/core.js:318:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 401,
  headers: {
    'alt-svc': 'h3=":443"; ma=86400',
    'cf-cache-status': 'DYNAMIC',
    'cf-ray': '8c4c11f35c236e0a-YUL',
    connection: 'keep-alive',
    'content-length': '323',
    'content-type': 'application/json; charset=utf-8',
    date: 'Tue, 17 Sep 2024 21:08:11 GMT',
    server: 'cloudflare',
    'set-cookie': '__cf_bm=5W3dUKakzg82DAQFXGbmJQeV0Y2yNdS4qAhUjqLd4_I-1726607291-1.0.1.1-oIoXTUXwqHRI8iohoe9xb2_NtjUKKbPDGAk7SAPnaQp1MmzkgToxE2yYsyTxiV.osT_D2HxqySM1MXp0ZBrWdg; path=/; expires=Tue, 17-Sep-24 21:38:11 GMT; domain=.api.openai.com; HttpOnly; Secure; SameSite=None, _cfuvid=tQ7zcNc2Xog7rgM68l_C9nOEpM2l2ofhsUr.EmZHJF0-1726607291511-0.0.1.1-604800000; path=/; domain=.api.openai.com; HttpOnly; Secure; SameSite=None',
    'strict-transport-security': 'max-age=15552000; includeSubDomains; preload',
    vary: 'Origin',
    'x-content-type-options': 'nosniff',
    'x-request-id': 'req_499d8228fbc7f87a96bb5e514b0ff99a'
  },
  request_id: 'req_499d8228fbc7f87a96bb5e514b0ff99a',
  error: {
    message: 'Incorrect API key provided: sk-or-v1*************************************************************abf1. You can find your API key at https://platform.openai.com/account/api-keys.',
    type: 'invalid_request_error',
    param: null,
    code: 'invalid_api_key'
  },
  code: 'invalid_api_key',
  param: null,
  type: 'invalid_request_error'
}
```

Switching the Base URL to `https://openrouter.ai/api/v1` as in the [OpenRouter docs](https://openrouter.ai/docs/quick-start) fixes the issue.

**Comment by mayank-Pareek** [comment]
README.md was updated while resolving #4, please review this issue and check if instructions need more context.

**Comment by uday-rana** [comment]
Looks good
